(load "tracer.scm")
(load "ex-path.scm")
(load "test-check.scm")

(test-check "patho-trace"
  (run 12 (q)
    (fresh (x y t)
      (== q `(,x ,y ,t))
      ((tracer patho-clause) `(patho ,x ,y) t)))
  '((a b ((patho a b))) (b c ((patho b c))) (c a ((patho c a)))
    (a c ((patho b c) (patho a c)))
    (c b ((patho a b) (patho c b)))
    (b a ((patho c a) (patho b a)))
    (a a ((patho c a) (patho b a) (patho a a)))
    (a b ((patho a b) (patho c b) (patho b b) (patho a b)))
    (b b ((patho a b) (patho c b) (patho b b)))
    (c c ((patho b c) (patho a c) (patho c c)))
    (a c ((patho b c) (patho a c) (patho c c) (patho b c) (patho a c)))
    (a a ((patho c a) (patho b a) (patho a a) (patho c a) (patho b a) (patho a a)))))
